version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '8080:8080'
    container_name: frontend
  db:
    image: mysql:latest
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: 'when2block'
      MYSQL_USER: 'when2block'
      MYSQL_PASSWORD: 'bt4301grp2'
      MYSQL_ROOT_PASSWORD: 'bt4301grp2'
    ports:
      - 3306:3306
    volumes:
      - ./server/init:/docker-entrypoint-initdb.d
      - ./server/when2block-db:/var/lib/mysql

# Names our volume
volumes:
  when2block-db:
