version: "3.8"

services:
  client: 
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    volumes:
      - /client/node_modules
      - ./client:/client
    ports:
      - 8080:8080
    depends_on: 
      - server

  server: 
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server
    volumes:
      - /server/node_modules
      - ./server:/server
    ports:
      - 8081:8081
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: 'when2block'
      MYSQL_USER: 'when2block'
      MYSQL_PASSWORD: 'bt4301grp2'
      MYSQL_ROOT_PASSWORD: 'bt4301grp2'
    volumes:
      - ./server/init:/docker-entrypoint-initdb.d
      - ./server/when2block-db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  when2block-db: